name: CI Tests
on:
  push:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      functional_tests_group:
        description: Run arbitrary functional tests group by name or all (short and long) tests (default)
        required: true
        default: all

permissions: read-all

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@44be5a8381691b9a209404a3f45df8254f1ce08f # v1.1.2
        with:
          test-versions: 7.4-

  phpcs:
    runs-on: ubuntu-latest
    name: PHP Coding Standards
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@fcafdd6392932010c2bd5094439b8e33be2a8a09 # v2.37.0
        with:
          php-version: 8.4
      - name: Install composer
        run: composer install --no-interaction --prefer-dist
      - name: Run tests
        run: composer cs

  functional:
    runs-on: ${{ matrix.os }}
    name: Functional testing matrix - PHP ${{ matrix.php-version.php }} on ${{ matrix.os }}
    if: ${{ github.repository_owner == 'pantheon-systems' }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - php: "7.4"
          - php: "8.0"
          - php: "8.1"
          - php: "8.2"
          - php: "8.3"
          - php: "8.4"
        php-ini-values:
          - assert.exception=1, zend.assertions=1
      max-parallel: 4
    env:
      DEPENDENCIES: ${{ matrix.dependencies }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@fcafdd6392932010c2bd5094439b8e33be2a8a09 # v2.37.0
        with:
          php-version: ${{ matrix.php-version.php }}
          coverage: pcov
          ini-values: ${{ matrix.php-ini-values }}
      - name: Install composer
        run: composer update --no-interaction --prefer-dist
      - name: Functional Tests
        run: composer test
